name: .NET

on:
  push:
    branches: [ main ]

variables:
  buildConfiguration: 'Release'
  buildOutput: '.output' # Output directory for publish

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Concept/Concept
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Publish
      run: dotnet publish -c Release --no-build -o $(buildOutput)
    - name: Perform a Pester test from the Tests.ps1 file
      shell: pwsh
      run: |
          GCI -Recurse
    - name: Publish generated Blazor webassembly to Netlify
      uses: netlify/actions/cli@master
      env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_API_ID }}
      with:
          args: deploy --dir $(buildOutput)/wwwroot --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]' 
