name: .NET

on:
  push:
    branches: [ main ]
    
env:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    NETLIFY_SITE_ID: ${{ secrets.NETLIFY_API_ID }}
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Concept/Concept
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Publish
      run: dotnet publish -c Release --no-build -o publishoutput
    # Install netlify-cli
    - run: npm install netlify-cli 
      name: 'Install netlify-cli'
        
        
    - run: npx netlify deploy --prod --dir publishoutput/wwwroot --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
      name: 'Deploy site to Netlify'
